---

- name: Install packages
  yum:
    name: rsyslog
    state: latest
  notify:
    - restart rsyslog

- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    mode: '0644'
    owner: root
    group: root
    backup: no
  notify:
    - restart rsyslog

- name: Add RELP port to syslogd_port_t
  command: "/usr/sbin/semanage port -a -t syslogd_port_t -p tcp 2514"
  when: ansible_selinux.status == "enabled" and rsyslog_relp_enable
  failed_when: false
